version: '3.7'

services:
  blogback.api:
    image: ${DOCKER_REGISTRY-}blogbackapi
    build:
      context: .
      dockerfile: BlogBack.API/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 


  blogs:
    build: ./blogs-angular
    ports:
      - "4201:4200"
    command: |
      sh -c '
        ng serve --host 0.0.0.0 
      '


